### ISSUE TITLE
getFile returns Syntax Error  Unexpected '<'

### ISSUE THREAD

**Issue by dc99dc99** [node-strava/node-strava-v3#164]
Not 100% sure when this started happening, but all the requests from my app to the Strava API to retrieve the contents of routes have started throwing this error.  I am successfully able to hit the REST API directly.

When I look at the code, it looks like line 48 of AxiosHelper is defaulting to json, when the GPX/TSX files are XML.

` responseType: options.responseType || 'json', // Support different response types`

Is this a bug, or should I be setting responseType somehow? I can't immediately see a way to do that as the `args` are not converted into `options`. I would imagine the getFile should set a responseType option to `xml` or similar since all the GPX and TSX files are XML format.

**Comment by markstos** [comment]
@Kyle-Ski This seems related to the switch to using `axios`. Could you take a look?

**Comment by dc99dc99** [comment]
I've forked and will put in a fix in the meantime. If can raise a PR, I will.

**Comment by Kyle-Ski** [comment]
I think I narrowed it down to the _getFileHelper method in routes.js. @dc99dc99 does it look like this would also solve your issue, or what solution did you come up with? (I recently blew up my strava aip access and am on a new machine, haven't been able to test things in a little bit )

https://github.com/node-strava/node-strava-v3/blob/bug/route-xml-response-type/lib/routes.js#L39

**Comment by dc99dc99** [comment]
I haven't quite tested it yet, but your change, plus in the Axios js, pulling the response Type from the args into the options in the getEndpoint method. I don't think it'll get used otherwise  will it. I'm on my phone, but can test it later today

**Comment by dc99dc99** [comment]
Hopng you can help me here, because I've gone down a rabbit-hole trying to fix this issue, and I can't seem to climb back out.

I'm not at all familiar with debugging npm packages, but I have cloned the repo and got the code running locally, however it looks like the code in main is newer than the npm package and doesn't work. The first issue was that HttpClient, line 13 in the [npm repo](https://www.npmjs.com/package/strava-v3/v/2.2.1?activeTab=code) is 

`HttpClient.prototype.getEndpoint = function (endpoint, args, done) {`

The version in [github](https://github.com/node-strava/node-strava-v3/blob/main/lib/httpClient.js) is async 

`HttpClient.prototype.getEndpoint = async function (endpoint, args) {`

What I don't understand is that my application code, which depends on the npm version, and is quite old, uses `await` and clearly used to work, but the latest version in npm doesn't support this and even if I revert, I get a `done is undefined` or similar message because I'm trying to call that function without a callback function. What's even wierder is that the npm documentation says that I should be able to use *await* but the code *doesn't contain the async* version. My Node/js foo is very weak, so I'm missing something fundamental.

However, if I put that aside and try to build and run the new version, I get an error on [line 176 of httpClient](https://github.com/node-strava/node-strava-v3/blob/main/lib/httpClient.js#L176).

`{
  name: 'SyntaxError',
  message: "Unexpected 'u'",
  at: 1,
  text: 'undefined'
}`

When I debug (which took me a while to work out), I can see that the `response` object directly contains the json response, it is not contained in `response.body`, so indeed response.body is undefined.  Could this be a result of some refactoring someone has done that hasn't worked or yet been tested? I can fix this bug (and the text bug) and raise a PR, but perhaps this has other bugs in it?

So, I'm currently stuck with a version which may have bugs from github, or a version from npm that tells me I shouldn't be using `await`.

As I say, my node/js is very rusty and I just about get by. When I start looking at typescript and promise libraries, I quickly get lost.

Can you help me get out of this hole.

**Comment by Kyle-Ski** [comment]
Hey @dc99dc99 I have just been able to set up my new laptop and am also seeing the same error. Taking a look now

**Comment by Kyle-Ski** [comment]
I just pushed a change to this branch: [bug/route-xml-response-type](https://github.com/node-strava/node-strava-v3/tree/bug/route-xml-response-type). Do you mind testing your `strava.routes.getFile({id: ...})` with this change? I realize I don't have any route files in my Strava account and don't have Strava premium anymore to create one.

**Comment by dc99dc99** [comment]
I've actually managed to fix all the errors I came across and have getFile working. I had to remove the promise based call I had for that one and replace it with await.  

You can see the diff in my fork at https://github.com/node-strava/node-strava-v3/compare/main...dc99dc99:node-strava-v3:main

There were a few changes required to ensure the json body was returned, and the text body could also be returned. listRoutes didn't work without these changes (missing return, remove json parser etc)

..and some the linter suggested which I also took.  

I've published a scoped version to npm for now and have it working. I'll keep an eye on this and revert back to the main one once you have it all working. I have only tested the functions I use, which are athlete.listRoutes and route.getFIle, so others may not work.

**Comment by dc99dc99** [comment]
> I just pushed a change to this branch: [bug/route-xml-response-type](https://github.com/node-strava/node-strava-v3/tree/bug/route-xml-response-type). Do you mind testing your `strava.routes.getFile({id: ...})` with this change? I realize I don't have any route files in my Strava account and don't have Strava premium anymore to create one.

yours looks better than mine for json parsing, but I think you may still be missing a return statement and parsing the `args` to the `options`. I can pull and test your branch once you think you have a working version based on my changes.

**Comment by Kyle-Ski** [comment]
Just updated the branch with `responseType` as argument you can pass to your methods so this will work now: `strava.routes.get({id: ... , responseType: 'text'` Let me know when you get a chance to test it out!

**Comment by dc99dc99** [comment]
My changes are a little messy, but for clarity, I think you're still missing a return keyword here

https://github.com/node-strava/node-strava-v3/blob/3a0c8f44d5f5d2c422df2eaa41fe7f3c2a95d83b/lib/routes.js#L23

Plus the missing assignment of args to options.

**Comment by Kyle-Ski** [comment]
Good catch on the return. And I think these assignments should handle the args to options no?

```
var options = { 
    url: endpoint,
    responseType: args.responseType || 'json'
   }
```

**Comment by dc99dc99** [comment]
Yes, looks good now. I'll test tomorrow and confirm it works. Thanks for
looking at it so quickly

**Comment by dc99dc99** [comment]
Hi,

 You're missing a check for json responseType in httpClient.js line 187. Without it, it still tries to JSON.parse the xml of the GPX. Also the Axios `response` doesn't contain a body field. The `response` is the body.

```
// parse the raw JSON string with big-integer reviver for 16+ digit numbers
    if(options.responseType=='json'){
      return JSON.parse(response, (key, value) => {
        if (typeof value === 'string' && /^\d{16,}$/.test(value)) {
          return JSONbig.parse(value)
        }
        return value
      })
    }else{
      return response
    }
```
Also on line 183, similarly, I don't think the check for `!response.body` is doing anything, because response doesn't contain a body.  When I change the code above, the route retrieval works. I would have to fiddle with eslint.config and yarn to get the tests working and try it all out. Are you able to test it, or you have no access?

**Comment by Kyle-Ski** [comment]
Thanks for taking a look and testing it with an XML file. I have a theory about the tests not working properly actually, I need to confirm on my other branch. So don't worry too much about them right now.

**Comment by Kyle-Ski** [comment]
@markstos I think we've squashed the bug. I created a PR linking to this issue 👍

**Comment by markstos** [comment]
@dc99dc99 Can you test the proposed fix in #165 before we merge it ?

**Comment by dc99dc99** [comment]
Will do. I got distracted trying to fix up the data that got cached my end
when the call was broken and applying my temporary fixes to unblock my
users.

This was just completed yesterday, so I should get a chance to test yours
today or tomorrow.

David

**Comment by markstos** [comment]
Closing because linked PR was merged.
